export const GET_COURSES_RESPONSE = 'GET_COURSES_RESPONSE';
export const GET_COURSE_RESPONSE = 'GET_COURSE_RESPONSE';
export const ADD_NEW_COURSE_RESPONSE = 'ADD_NEW_COURSE_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
